### PR TITLE
Add notebooks &c. from old repo

### PR DESCRIPTION
**Pull request by leehart**

### CODE REVIEW

**Comment by leehart** [comment]
Manubot workflow is failing on `Install Spellcheck`.

Btw, PR #2 is building fine with `lang: en-GB`

Might be transient:
```
Err:18 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease
  403  Forbidden [IP: 195.135.221.134 80]
```

[I get 403 on that URL from anywhere.]

**Comment by leehart** [comment]
Looks like this URL is now working, so I'll try retriggering the workflow.
```
http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04
```

**Review by hardingnj — CHANGES_REQUESTED** [review]
Thanks Lee. 
LGTM, with the exception of the setup package. 

I'm going to follow Alistair's suggestion and present as a module, which I will file as a separate PR to this, just to keep things a bit cleaner. 

So this just needs the `release_data.py` and the `__init__.py` removing- then we are good to go I think.

**Review by hardingnj — APPROVED** [review]
Thanks Lee- LGTM.

**Pull request merged**
