### PR TITLE
q41 add text re: wild sample and crosses.

### PR DESCRIPTION
**Pull request by hardingnj**
This supersedes #33 

Hi Chris, took the liberty of 
- renaming the notebook for consistency 
- removing the addition of the cross metadata.
Then I squashed a few commits.

### CODE REVIEW

**Comment by hardingnj** [comment]
Hi @cclarkson , is this ready for review? or is there more you'd like to do here

**Comment by cclarkson** [comment]
Hi @hardingnj, I have updated the results and methods with the correct crosses info. There's just one section I'd like to add to the methods before this is ready for review/merge, which is @jonbrenas's methods for picking the new cross fathers. 

@jonbrenas, it is probably easiest if you just send me a sentence/few sentences and I will incorporate them to this PR.

**Comment by cclarkson** [comment]
@hardingnj @leehart  - this is now finally ready for review.

**Review by hardingnj — COMMENTED** [review]
This looks good to me. I can't officially approve because I opened the PR: can someone else do so + merge? Thanks!

**Review by leehart — APPROVED** [review]

**Pull request merged**
