### PR TITLE
q77: notebook providing numbers breakdown per qc stage.

### PR DESCRIPTION
**Pull request by hardingnj**
Also should provide numbers for sequencing techs.

### CODE REVIEW

**Comment by hardingnj** [comment]
Added:
- sequence technology work
- what happened to phase 2 samples cc @cclarkson

**Comment by hardingnj** [comment]
ready for review

**Review by cclarkson — APPROVED** [review]

**Comment by cclarkson** [comment]
@hardingnj - looks good to me. Let's discuss how to report etc.

**Review by cclarkson — CHANGES_REQUESTED** [review]
Hi @hardingnj , could we get these stats for wild-caught and crosses separately? Could we also discuss what the categories mean e.g. FILTER_second_rep_hi_skew filter

**Comment by hardingnj** [comment]
Sure- I'm on AL today- but let's talk on Monday at the catch up?

**Comment by hardingnj** [comment]
Hi Chris- just getting a bit lost in PRs, so will merge this and address the point you raised at the next catch up.

**Pull request merged**
