### PR TITLE
Generate feature accessibility tables q86, accessibility plots, divergence plots

### PR DESCRIPTION
**Pull request by hardingnj**

### CODE REVIEW

**Comment by hardingnj** [comment]
Accessibility figure to follow to this PR

**Comment by hardingnj** [comment]
ready for review

**Comment by cclarkson** [comment]
Hi @hardingnj,

This looks great, can be merged, just a couple of comments:
- a single table, even at this stage, would make the accessibility easy to eyeball.
- when we discussed this a while ago, you mentioned making the 'whole genome scan plot' more compact by sitting across just two rows. Is this still something you want to add here?

**Comment by hardingnj** [comment]
working on adding text around genome accessibility and including all exome in features.

**Comment by hardingnj** [comment]
Merging for now- need to reorg notebook names and tables for clarity etc

**Pull request merged**
