### PR TITLE
Add allele counts cloud storage option

### PR DESCRIPTION
**Pull request by leehart**
- Fixes a missing `[` in the `species_group` param. I would personally label as `species_groups` instead.
- Adds option to store outputs on cloud (which has been run) or store locally (which has not been run/tested)
- Added consolidated metadata and checks. Maybe this is overkill/unnecessary here? Following previous behaviour.

Probably want to permanently remove the previous outputs from the repo too, before merging with master, but need to remind myself how. Maybe a new branch is simplest? Maybe a simple removal would suffice?

Didn't zip the zarrs, because I'm not so familiar with interacting with zipped zarrs. I gather there must be a storage size reduction, maybe at an interaction cost. Maybe if the consolidated metadata and other checks are not wanted, then zipped zarrs make perfect sense, especially if we want to decrease the storage size, and handling zipped zarrs isn't overly complicated.

### CODE REVIEW

**Comment by hardingnj** [comment]
Thanks Lee. 

- The main (only!?) advantage of zipped `zarr`s is that they are much easier to copy and move around, there are no space advantages, the compression should be efficient regardless. 

- Yes, the files should be removed. The best way is to `rebase -i` and remove them from the offending commit. 

- Thanks for the local storage update. 

- Good catch on `[`, suggests that the notebook should be rerun completely through.

- Always happy for consolidated MD checks!

**Comment by cclarkson** [comment]
@leehart, are we going to remove the write locally option here before merging this with the parent branch?

**Comment by leehart** [comment]
@cclarkson Since this PR now has conflicts,  and it only needs to add the cloud option, I would suggest solving & merging #34 first, then I can simply add the cloud-store amend to whatever is in master, as a new PR. I can also simplify the Util class wrapper as well, if it hasn't been done. That seems the simplest to me, rather than trying to make this PR compatible with its parent.

**Comment by leehart** [comment]
Alternatively, the cloud-store amend (non-zipped and checks for metadata, etc.) could be integrated into #34, if it's easy enough to see what needs to be added. I don't mind either way, but my feeling is to scrap this PR rather than update it.

**Comment by cclarkson** [comment]
@leehart - Now the local files have been expunged from the branch I'll add your cloud store code to #34, then maybe you can review it, then we can scrap this PR?

**Comment by leehart** [comment]
> @leehart - Now the local files have been expunged from the branch I'll add your cloud store code to #34, then maybe you can review it, then we can scrap this PR?

Sounds good to me. Thanks Chris!

NB: https://discourse.malariagen.net/t/datalab-capacity-issues/384

**Comment by hardingnj** [comment]
So we can close this PR? Feel free to reopen if I have misunderstood!

**Comment by leehart** [comment]
I won't delete the `LH_cc_allele_count_version` branch until I'm sure Chris has got all the code we need in #34

**Comment by leehart** [comment]
OK, looks like #34 has the cloud storage code now. Removing branch `LH_cc_allele_count_version`

**Pull request closed without merging**
