### PR TITLE
Add setup module as module, not packaged

### PR DESCRIPTION
**Pull request by hardingnj**
As discussed on call

Decided to keep class structure, but simplify to module.

### CODE REVIEW

**Comment by leehart** [comment]
I'm hesitating because `release` in `release_data()` can be a verb, and I still have much to learn about Python best practices, amongst other things.

**Comment by hardingnj** [comment]
Cool- happy to rename for clarity. What's the PEP guideline about verbs?

**Comment by alimanfoo** [comment]
LGTM. Couple of soft suggestions, happy with whatever you prefer:

* Still reckon you could do without a class and just provide functions and variables. 
* Could just name module "ag3" if you wanted to be really concise. 
* Could shorten function names a little. 
* Total nit, I know this is something we go back and forth on, but prefer "sample_set" to "sampleset".

E.g.:

```
import ag3
ag3.all_sample_sets
ag3.wild_sample_sets
ag3.samples(...)
ag3.site_filters(...)
ag3.snp_variants(...)
ag3.snp_calldata(...)
```

**Comment by cclarkson** [comment]
Hi guys, any idea on an eta for the review on this - just wondering if it is worth me re-writing the map code to work without the module or wait for it to be merged?

**Comment by alimanfoo** [comment]
Happy for @hardingnj to merge as-and-when sees fit.

**Comment by hardingnj** [comment]
I've incorporated Alistair's suggestions, so please feel free to review + merge.

**Pull request merged**
