### PR TITLE
Q89 male hets

### PR DESCRIPTION
**Pull request by hardingnj**
I'm getting an unexpected `Killed Worker` error. Is this what you experienced @jonbrenas ?

I'm stumped!

### CODE REVIEW

**Comment by hardingnj** [comment]
Hmm- some progress. It only seems to happen when I use `allel.GenotypeDaskArray`. Otherwise runs as expected. 

In the logs I find:

```
distributed.worker - ERROR - maximum recursion depth exceeded Traceback (most recent call last): File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 905, in handle_scheduler comm, every_cycle=[self.ensure_communicating, self.ensure_computing] File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 456, in handle_stream msgs = await comm.read() File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 222, in read frames, deserialize=self.deserialize, deserializers=deserializers File "/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py", line 69, in from_frames res = _from_frames() File "/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py", line 55, in _from_frames frames, deserialize=deserialize, deserializers=deserializers File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads value = _deserialize(head, fs, deserializers=deserializers) File "/opt/conda/lib/python3.7/site-
...
```

However- if I return the dask object from the function `load_calldata_by_sampleset` _then_ pop _that_ into `allel.GenotypeDaskArray` it works as expected.  

Which I think is something to do with the `init()` not being handled properly in distributed. Though I suspect I need @alimanfoo to dianose fully. My understanding of scope etc in python is limited. 

For the moment though deleting two lines in `phase3_data.py` fixes my issue. Unsure if this is the same mysterious cause that @jonbrenas and @alimanfoo observed.

**Comment by alimanfoo** [comment]
Using dask distributed does mean that some pickling of objects and functions happens to move them to workers, so it could be there is a problem with that. Would it be possible to make a small reproducible example notebook?

**Comment by hardingnj** [comment]
I'll do my best!

**Comment by hardingnj** [comment]
Have been trying- but no luck unfortunately... just seems to work as expected. I think I'll just implement the work around and press on.

**Comment by hardingnj** [comment]
superseded by #18

**Comment by leehart** [comment]
Deleting branch.

**Pull request closed without merging**
