### PR TITLE
Produce location colours. Store as YAML. Make available as dict from ag3.py

### PR DESCRIPTION
**Pull request by leehart**

### CODE REVIEW

**Comment by leehart** [comment]
Plan:
- [x] Make YAML nest country > location (instead of concatenated label)
- [x] Make colours RGBA hex (e.g. `#11223344`) instead of Python tuples
- [x] Import YAML into `ag3.py` and test usage as dict

**Comment by leehart** [comment]
@hardingnj @cclarkson Samples from Cameroon with the same lat-long for different locations:
image

**Comment by cclarkson** [comment]
@leehart, @hardingnj - apologies, you're right about the unique locations. There are 126 locations and a 124 unique lat/lons, this is difference is generate by the Cameroonian samples @leehart has highlighted above.

**Review by hardingnj — APPROVED** [review]
Thanks Lee- terrific stuff

**Pull request merged**
