### PR TITLE
Create allele counts for PCA/UMAP

### PR DESCRIPTION
**Pull request by cclarkson**
This PR is based on Nick's [PR](https://github.com/malariagen/ag1000g-phase3-data-paper/pull/31) but puts the code into a notebook (so I can understand and run it easily) and addresses the comments made on the review of that PR.

There is at least one aspect that might need some discussion here - I have used the 'free' region of 3L for all three groups/masks. I feel that this is easier to defend than using the 3L+3R free region for gamb_colu but  just 3L for arab and gamb_colu_arab. Happy to change this if other opinions are out there?

I will base the UMAP branch off this for now.

### CODE REVIEW

**Comment by leehart** [comment]
I've submitted a [PR](https://github.com/malariagen/ag1000g-phase3-data-paper/pull/35) against this branch, with some ponderings.

**Comment by hardingnj** [comment]
That should do it. Unsure how it will affect Lee's PR against this branch though.

**Comment by leehart** [comment]
Cool, thanks Nick. I'll just have to resolve the conflicts or reapply the amends, which aren't complicated, and I had to change them anyway, so no worries.

**Comment by hardingnj** [comment]
Hi @cclarkson FWIW I think the best way is to be more explicit: 

`df.eval("Species in ('gambcolu', 'arabiensis', 'intermediate')")`

I haven't pushed the change, but I think for a single line it's probably not worth it. Could you copy/paste when making your changes? Thanks!

**Comment by cclarkson** [comment]
@hardingnj  - no worries, will do.

**Review by hardingnj — CHANGES_REQUESTED** [review]
Thanks Chris to summarise yesterday:

- [x] 3R/3L for gamb_colu
- [x] Fix eval string (my comment above)
- [x] Add LD pruning
- [x] Tidy up function import via `Util` (happy to help with this when ready)

**Comment by cclarkson** [comment]
@hardingnj - I'm a little concerned, I pulled to update my branch with the changes you had made but I can still see the allele count zarrs locally. Can I just delete them before I push?

**Comment by hardingnj** [comment]
If you run `git status` they should be untracked? If so, you can safely delete.

If not- run a git log and post any commit in which they have been altered?

**Comment by cclarkson** [comment]
Hi @hardingnj - if you have a minute could you give me a hand cleaning up the function import Util hangover?

**Comment by hardingnj** [comment]
no worries- I'll have a look first thing

**Review by hardingnj — APPROVED** [review]

**Comment by leehart** [comment]
Why use a logger and then don't include the logs? Or why use a logger at all, with all its overhead, when the logs can simply been recorded/printed in the notebook, which seems more convenient and straightforward to me?

**Comment by leehart** [comment]
```
module_path = "../../notebooks/"
```
is not used

**Comment by hardingnj** [comment]
In this case just because I wanted some info about how long each step was taking. 

But, yes, it's certainly overhead. 

> ```
> module_path = "../../notebooks/"
> ```
> 
> is not used

Good catch. Should be removed.

**Comment by leehart** [comment]
This comment is obsolete now:
```
when I get permissions to write to cloud un-hash the zarr writing bits
```

Wrt to timing operations, I've found the `%%time` cell magic handy.

**Comment by cclarkson** [comment]
@leehart  and @hardingnj  - I'll remove the obsolete code now. Shall I leave the logger?

**Comment by hardingnj** [comment]
Let's keep the logger. Good to have a handle on how long each step is taking

**Comment by cclarkson** [comment]
@hardingnj - cool, I guess we're good to merge now?

**Comment by hardingnj** [comment]
thanks!

**Comment by leehart** [comment]
1. Any thoughts on deleting branches after merging PRs? https://github.com/malariagen/ag1000g-phase3-data-paper/branches/all
2. ~Do these allele counts incorporate genotype results from samples in the AG1000G-X sample set, which might not be representative?~ [Looks like this is covered by `sample_sets = v3.all_wild_sample_sets`, which is `[x for x in self._all_sample_sets if x != "AG1000G-X"]`.]

**Comment by hardingnj** [comment]
Just a note to add that we want to 
a) Rename this notebook to be consistent with naming
b) Also report sample_ids of the different species groups to avoid propagation upstream.

**Comment by hardingnj** [comment]
(then we can delete this branch)

**Pull request merged**
