### PR TITLE
tidy data and content/tables

### PR DESCRIPTION
**Pull request by hardingnj**
Reorganise of repo structure.

`data` contains some files that should be in `content/tables`. The following need to happen before review:

- [x] Add readme describing what lives where
- [x] Adjust seq tech notebook to read data from new location
- [x] Adjust performance eval notebooks to write to correct locations
- [x] Adjust X MER notebook to write to new loc
- [x] Change accessibility notebook to write to new location

### CODE REVIEW

**Comment by hardingnj** [comment]
NB: This PR is based from the `split-methods` branch, which hopefully should be merged soon.

**Comment by hardingnj** [comment]
Lots of moved files- but the changes are relatively small, just renames and reruns for the most part.

**Comment by hardingnj** [comment]
This is reasonably high priority for merging- otherwise we run the risk of getting into conflicts!

**Review by leehart — APPROVED** [review]
LGTM. Thanks Nick

**Comment by leehart** [comment]
Deleted `tidy_data_dir` branch

**Pull request merged**
